networks:
    app-network:
        driver: bridge

services:
    gateway:
        build:
            context: .
            dockerfile: docker/docker.gateway
        ports:
            - "8080:8080"
        networks:
            - app-network
        # environment:
        #     - PORT=8080
        #     - AUTH_SERVICE_NAME=AUTH_SERVICE
        #     - AUTH_SERVICE_PORT=8801
        #     - AUTH_SERVICE_HOST=127.0.0.1
        #     - JWT_ACCESS_EXPIRES=60d
        #     - JWT_REFRESH_EXPIRES=180d
        #     - JWT_SECRET=JOIN_NEXON
        #     - COOKIEAGE=24 * 60 * 60 * 1000
        #     - EVENT_SERVICE_NAME=EVENT_SERVICE
        #     - EVENT_SERVICE_PORT=8802
        #     - EVENT_SERVICE_HOST=127.0.0.1
        depends_on:
            - auth
            - collection
        # env_file:
        #     - gateway/src/main/resources/application.yml
    eureka:
        build:
            context: .
            dockerfile: docker/docker.eureka
        ports:
            - "8761:8761"
        networks:
            - app-network
        depends_on:
            - gateway
        # env_file:
        #     - eureka/src/main/resources/application.yml

    auth:
        build:
            context: .
            dockerfile: docker/docker.auth
        ports:
            - "8081:8081"
        networks:
            - app-network
        # env_file:
        #     - auth/src/main/resources/application.yml
        # environment:
        #     - PORT=8801
        #     - HOST=127.0.0.1
        #     - DB_URL=mongodb+srv://join_nexon_user:987987@joinnexon.ygtkmie.mongodb.net/?retryWrites=true&w=majority&appName=joinNexon

    collection:
        build:
            context: .
            dockerfile: docker/docker.collection
        ports:
            - "8082:8082"
        networks:
            - app-network
        # env_file:
        #     - collection/src/main/resources/application.yml
