server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: collection
          uri: lb://collection
#          uri: http://localhost:8081
          predicates:
            - Path=/collection/**
#        - id: coupon
#          uri: lb://COUPON
#          predicates:
#            - Path=/coupon/**

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /v3/swagger-ui.html
    config-url: /v3/swagger-ui.html/swagger-config
    urls:
      - url: /v3/api-docs
        name: collection
#      - url: /partners/v3/api-docs
#        name: partners
#      - url: /cms/v3/api-docs
#        name: cms
