server:
    port: 8083
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true

# DB ??
spring:
    application:
        name: collection
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://ls-47159192c28754e3445812e18a1e26526408e5d5.cdyy6u06m4x3.ap-northeast-2.rds.amazonaws.com:3306/newsCollection?serverTimezone=Asia/Seoul
        username: dbmasteruser
        password: sbtmdlqslek3!

# mybatis
mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    config-location: classpath:mybatis-config.xml

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
        fetch-registry: true
        register-with-eureka: true

openapi:
    info:
        title: collection
        description: collection
        version: 1.0

springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html
